apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: prometheus-server

  ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-alert-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: kube-prometheus-alert-pv
